/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 12 10:17:04 GMT 2025
 */

package org.apache.openjpa.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import org.apache.openjpa.lib.util.LRUMap;
import org.apache.openjpa.util.CacheMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CacheMap_ESTest extends CacheMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      cacheMap0.putAll((Map) cacheMap0, false);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      cacheMap0.cacheMapOverflowRemoved(hashMap0, hashMap0);
      boolean boolean0 = cacheMap0.containsValue(hashMap0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      boolean boolean1 = cacheMap0.containsValue((Object) null);
      assertTrue(boolean1);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false);
      boolean boolean0 = cacheMap0.containsValue((Object) null);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      cacheMap0.putIfAbsent(object0, object0);
      boolean boolean0 = cacheMap0.containsValue(object0);
      assertTrue(boolean0);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      CacheMap cacheMap0 = new CacheMap();
      cacheMap0.cacheMapOverflowRemoved(hashMap0, hashMap0);
      boolean boolean0 = cacheMap0.containsKey(hashMap0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      Function<CacheMap, CacheMap> function0 = Function.identity();
      Object object1 = cacheMap0.computeIfAbsent(object0, function0);
      boolean boolean1 = cacheMap0.containsKey(object1);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      LRUMap lRUMap0 = new LRUMap(264, 264);
      cacheMap0.putIfAbsent(lRUMap0, lRUMap0);
      boolean boolean0 = cacheMap0.isEmpty();
      assertEquals(1000, cacheMap0.getCacheSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = cacheMap0.put((Map) cacheMap0, (Object) cacheMap0, (Object) cacheMap0);
      assertNull(object0);
      
      cacheMap0.clear();
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      boolean boolean0 = cacheMap0.pin(cacheMap0);
      assertFalse(boolean0);
      
      cacheMap0.clear();
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false);
      Object object0 = new Object();
      cacheMap0.putIfAbsent(object0, object0);
      Object object1 = cacheMap0.remove(object0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertNotNull(object1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      Object object1 = cacheMap0.remove(object0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertNull(object1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      CacheMap cacheMap1 = new CacheMap(true);
      Object object0 = cacheMap1.put((Map) cacheMap0, (Object) cacheMap0, (Object) cacheMap0);
      assertNull(object0);
      
      cacheMap1.putAll((Map) cacheMap0, false);
      assertEquals(1000, cacheMap1.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = cacheMap0.put((Map) cacheMap0, (Object) cacheMap0, (Object) cacheMap0);
      assertNull(object0);
      
      cacheMap0.putAll((Map) cacheMap0, false);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      LRUMap lRUMap0 = new LRUMap();
      Object object0 = cacheMap0.put(lRUMap0, lRUMap0);
      assertNull(object0);
      
      Object object1 = cacheMap0.put(lRUMap0, lRUMap0);
      assertNotNull(object1);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false, 0);
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      Object object0 = cacheMap0.put(hashMap0, hashMap0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false, 0);
      // Undeclared exception!
      try { 
        cacheMap0.getOrDefault(cacheMap0, cacheMap0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      cacheMap0.putIfAbsent(object0, object0);
      Object object1 = cacheMap0.putIfAbsent(object0, object0);
      boolean boolean0 = cacheMap0.pin(object1);
      assertTrue(boolean0);
      
      Object object2 = cacheMap0.remove(object1);
      assertNotNull(object2);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      CacheMap cacheMap0 = new CacheMap(false);
      cacheMap0.cacheMapOverflowRemoved(hashMap0, hashMap0);
      Object object0 = cacheMap0.get(hashMap0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      Function<String, String> function0 = Function.identity();
      Object object1 = cacheMap0.computeIfAbsent(object0, function0);
      boolean boolean1 = cacheMap0.unpin(object1);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      HashMap<CacheMap, CacheMap> hashMap0 = new HashMap<CacheMap, CacheMap>();
      boolean boolean0 = cacheMap0.unpin(hashMap0);
      assertFalse(boolean0);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      HashMap<CacheMap, CacheMap> hashMap0 = new HashMap<CacheMap, CacheMap>();
      cacheMap0.putIfAbsent(object0, hashMap0);
      boolean boolean0 = cacheMap0.pin(object0);
      assertTrue(boolean0);
      
      cacheMap0.putAll((Map) cacheMap0, true);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      assertFalse(boolean0);
      
      Function<String, String> function0 = Function.identity();
      Object object1 = cacheMap0.computeIfAbsent(object0, function0);
      boolean boolean1 = cacheMap0.pin(object1);
      assertTrue(boolean1);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      Object object0 = new Object();
      boolean boolean0 = cacheMap0.pin(object0);
      boolean boolean1 = cacheMap0.pin(object0);
      assertTrue(boolean1 == boolean0);
      assertEquals(1000, cacheMap0.getCacheSize());
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      int int0 = cacheMap0.getSoftReferenceSize();
      assertEquals((-1), int0);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      cacheMap0.setSoftReferenceSize(0);
      int int0 = cacheMap0.getSoftReferenceSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      cacheMap0.setSoftReferenceSize((-580));
      assertEquals(1000, cacheMap0.getCacheSize());
      assertEquals((-1), cacheMap0.getSoftReferenceSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      assertEquals(1000, cacheMap0.getCacheSize());
      
      cacheMap0.setCacheSize((-59));
      int int0 = cacheMap0.getCacheSize();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      int int0 = cacheMap0.getCacheSize();
      assertEquals(1000, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      cacheMap0.setCacheSize(0);
      assertEquals(0, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      cacheMap0.setSoftReferenceSize(0);
      assertEquals(0, cacheMap0.getSoftReferenceSize());
      
      cacheMap0.cacheMapOverflowRemoved(cacheMap0, (Object) null);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      cacheMap0.toString();
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      cacheMap0.getPinnedKeys();
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      boolean boolean0 = cacheMap0.isEmpty();
      assertTrue(boolean0);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false, 0);
      cacheMap0.isLRU();
      assertEquals(0, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      cacheMap0.softMapValueExpired((Object) null);
      assertTrue(cacheMap0.isLRU());
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(true);
      Set set0 = cacheMap0.keySet();
      assertTrue(cacheMap0.isLRU());
      assertEquals(1000, cacheMap0.getCacheSize());
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false, (-1554));
      Function<Object, Object> function0 = Function.identity();
      Set set0 = cacheMap0.entrySet();
      cacheMap0.softMapOverflowRemoved(function0, set0);
      assertEquals(0, set0.size());
      assertEquals((-1), cacheMap0.getCacheSize());
      assertFalse(cacheMap0.isLRU());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      cacheMap0.values();
      assertEquals(1000, cacheMap0.getCacheSize());
      assertFalse(cacheMap0.isLRU());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false, 1, (-1), 1);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Object object0 = cacheMap0.putIfAbsent(hashMap0, hashMap0);
      assertNull(object0);
      
      HashMap<String, String> hashMap1 = new HashMap<String, String>(7, 7);
      Function<String, String> function0 = Function.identity();
      cacheMap0.computeIfAbsent(hashMap1, function0);
      assertEquals(1, cacheMap0.getCacheSize());
      assertFalse(cacheMap0.isLRU());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap(false);
      Object object0 = new Object();
      Object object1 = cacheMap0.remove(object0);
      assertFalse(cacheMap0.isLRU());
      assertNull(object1);
      assertEquals(1000, cacheMap0.getCacheSize());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CacheMap cacheMap0 = new CacheMap();
      HashMap<CacheMap, CacheMap> hashMap0 = new HashMap<CacheMap, CacheMap>();
      cacheMap0.cacheMapOverflowRemoved(hashMap0, hashMap0);
      cacheMap0.putAll((Map) cacheMap0);
      assertFalse(cacheMap0.isLRU());
      assertEquals(1000, cacheMap0.getCacheSize());
  }
}
